# Generated by Django 3.2.11 on 2022-01-22 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='submission',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
